### ISSUE TITLE
Export modal not showing up

### ISSUE THREAD

**Issue by Hexodus** [vuetifyjs/theme-generator#25] opened 2021-04-15 11:46 UTC
If I try it on:
https://theme-generator.vuetifyjs.com/
and klick on export, then no modal shows up anymore.

**Comment by jacekkarczmarczyk** [comment] 2021-04-15 11:50
Duplicate of https://github.com/vuetifyjs/theme-generator/issues/9

**Closed by jacekkarczmarczyk** 2021-04-15 11:50 UTC
